
#Sandmastery Config. This config is synced between server and client.
[sandmastery]
	#How many ticks between projectiles at 1 ribbon allocated in ticks. (1 second = 20 ticks)
	#Range: 24 ~ 1000
	projectileCooldown = 100
	#Hydration cost is tied to sand cost, how many units of hydration are used per unit of sand charge
	#Range: 0.5 ~ 100.0
	hydrationCostMultiploer = 1.5
	#Charge cost multiplier is multiplied by the base cost to determine charge cost per tick
	#Range: 1 ~ 1000
	chargeCostMultiplier = 2
	#Starting hydration a player has when they spawn into the world for the first time
	#Range: 1 ~ 100000
	startingHydration = 10000
	#Max hydration a player can have
	#Range: 1 ~ 100000
	maxHydration = 10000
	#How long overmastery lasts in minutes
	#Range: 1 ~ 720
	overmasteryDuration = 120
	#The threshold at which a player will start to become dehydrated (percentage of max)
	#Range: 0.1 ~ 100.0
	dehydrationThreshold = 0.1
	#Should the player be given a qido on first login?
	qidoOnFirstLogin = false
	#How much hydration should a qido restore in a single fill?
	#Range: 1 ~ 1000000
	qidoMaxFill = 10000

