name: General Issue
description: Report a bug or problem with Cosmere
body:
  - type: markdown
    attributes:
      value: "*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*"
  - type: textarea
    attributes:
      label: Issue description
      description: A clear and concise description of the issue and if appropriate what the expected outcome should have been.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: If there are specific steps that need to be taken to reproduce the issue list them here.
      placeholder: |
        1. Start by doing...
        2. Next do...
        3. See result described above
  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft version
      description: What version of Minecraft are you using?
      options:
        - 1.20.1 (Latest)
        - 1.19.2
        - 1.19.0 or 1.19.1 (No longer being developed)
        - 1.18.x or earlier (No longer being developed)
    validations:
      required: true
  - type: input
    attributes:
      label: Modloader version
      description: What version of Neo or Forge are you using?
      placeholder: e.g. 43.1.3
    validations:
      required: true
  - type: input
    id: cosmere-version
    attributes:
      label: Cosmere version
      description: What version of Cosmere are you using? You can copy paste the file name of the Cosmere mod if needed.
      placeholder: e.g. build 72
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other relevant versions
      description: If this issue is related to any other mods list their versions here.
  - type: input
    attributes:
      label: "If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)"
      description: "Please provide a [mclog](https://mclo.gs) / [gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. (Make sure that it isn't set to expire!)"
